steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    dir: 'src/stripe-webhook-handler'
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/$PROJECT_ID/cofound-agents-registry/delivery-agent:$SHORT_SHA', '.']

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: ['push', 'europe-west2-docker.pkg.dev/$PROJECT_ID/cofound-agents-registry/delivery-agent:$SHORT_SHA']

  # 3. Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'delivery-agent'
      - '--image'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cofound-agents-registry/delivery-agent:$SHORT_SHA'
      - '--region'
      - 'europe-west2'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'cofound-agents-deploy@$PROJECT_ID.iam.gserviceaccount.com'
      - '--no-allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cofound-agents-registry/delivery-agent:$SHORT_SHA'
