steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend'
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/$PROJECT_ID/cofound-agents-registry/travel-agent:$SHORT_SHA', '.']

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend'
    args: ['push', 'europe-west2-docker.pkg.dev/$PROJECT_ID/cofound-agents-registry/travel-agent:$SHORT_SHA']

  # 3. Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Backend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'travel-agent'
      - '--image'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cofound-agents-registry/travel-agent:$SHORT_SHA'
      - '--region'
      - 'europe-west2'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'cofound-agents-deploy@$PROJECT_ID.iam.gserviceaccount.com'
      - '--no-allow-unauthenticated'
      - '--set-secrets'
      - 'STRIPE_SECRET_KEY=travel-agent-stripe-secret-key:latest,FIREBASE_APPLICATION_CREDENTIALS=travel-agent-firebase-creds:latest,GOOGLE_CLIENT_ID=travel-agent-google-client-id:latest,GOOGLE_CLIENT_SECRET=travel-agent-google-client-secret:latest,GOOGLE_OAUTH_CALLBACK_URL=travel-agent-oauth-callback:latest,GCP_PROJECT_ID=travel-agent-google-client-id:latest'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cofound-agents-registry/travel-agent:$SHORT_SHA'
